# Generated by Django 5.2.5 on 2025-08-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SafraAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano de início da safra agrícola.', verbose_name='Ano da Safra')),
                ('uf', models.CharField(help_text='Sigla da Unidade Federativa (UF).', max_length=2, verbose_name='Estado (UF)')),
                ('produto', models.CharField(help_text='Nome da cultura (ex: Soja, Milho).', max_length=255, verbose_name='Produto Agricola')),
                ('area_plantada_ha', models.FloatField(blank=True, help_text='Área plantada em hectares.', null=True, verbose_name='Área Plantada (ha)')),
                ('producao_toneladas', models.FloatField(blank=True, help_text='Produção em toneladas.', null=True, verbose_name='Produção (t)')),
                ('produtividade_kg_ha', models.FloatField(blank=True, help_text='Produtividade em quilogramas por hectare.', null=True, verbose_name='Produtividade (kg/ha)')),
            ],
            options={
                'verbose_name': 'Safra Anual',
                'verbose_name_plural': 'Safras Anuais',
                'unique_together': {('ano', 'uf', 'produto')},
            },
        ),
    ]
