# Generated by Django 5.2.5 on 2025-09-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Localidade')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'Localidade',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='SafraAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano de início da safra agrícola.', verbose_name='Ano da Safra')),
                ('uf', models.CharField(help_text='Sigla da Unidade Federativa (UF).', max_length=2, verbose_name='Estado (UF)')),
                ('produto', models.CharField(help_text='Nome da cultura (ex: Soja, Milho).', max_length=255, verbose_name='Produto Agricola')),
                ('area_plantada_ha', models.FloatField(blank=True, help_text='Área plantada em hectares.', null=True, verbose_name='Área Plantada (ha)')),
                ('producao_toneladas', models.FloatField(blank=True, help_text='Produção em toneladas.', null=True, verbose_name='Produção (t)')),
                ('produtividade_kg_ha', models.FloatField(blank=True, help_text='Produtividade em quilogramas por hectare.', null=True, verbose_name='Produtividade (kg/ha)')),
            ],
            options={
                'verbose_name': 'Safra Anual',
                'verbose_name_plural': 'Safras Anuais',
                'unique_together': {('ano', 'uf', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='DadoMeteorologicoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Medição')),
                ('precipitacao_mm', models.FloatField(blank=True, null=True, verbose_name='Precipitação Corrigida (mm/dia)')),
                ('temp_maxima_c', models.FloatField(blank=True, null=True, verbose_name='Temperatura Máxima a 2m (°C)')),
                ('temp_minima_c', models.FloatField(blank=True, null=True, verbose_name='Temperatura Mínima a 2m (°C)')),
                ('localidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidade', verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Dado Meteorológico Diário',
                'verbose_name_plural': 'Dados Meteorológicos Diários',
                'unique_together': {('localidade', 'data')},
            },
        ),
    ]
