# Generated by Django 5.2.5 on 2025-09-15 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoMeteorologica',
            fields=[
                ('codigo', models.CharField(help_text='Código único da estação meteorológica.', max_length=10, primary_key=True, serialize=False, verbose_name='Código da Estação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Estação')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('data_inicio_operacao', models.DateField(help_text='Data de início da operação da estação meteorológica.', verbose_name='Início da Operação')),
                ('uf', models.CharField(help_text='Sigla da Unidade Federativa (UF).', max_length=2, verbose_name='Estado (UF)')),
            ],
            options={
                'verbose_name': 'Estação Meteorológica',
                'verbose_name_plural': 'Estações Meteorológicas',
            },
        ),
        migrations.CreateModel(
            name='DadoMeteorologicoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Medição')),
                ('precipitacao_mm', models.FloatField(blank=True, null=True, verbose_name='Precipitação (mm)')),
                ('temp_maxima_c', models.FloatField(blank=True, null=True, verbose_name='Temperatura Máxima (°C)')),
                ('emp_minima_c', models.FloatField(blank=True, null=True, verbose_name='Temperatura Mínima (°C)')),
                ('umidade_media_porc', models.FloatField(blank=True, null=True, verbose_name='Umidade Média (%)')),
                ('estacao', models.ForeignKey(help_text='A estação à qual este dado pertence.', on_delete=django.db.models.deletion.CASCADE, to='core.estacaometeorologica', verbose_name='Estação Meteorológica')),
            ],
            options={
                'verbose_name': 'Dado Meteorológico Diário',
                'verbose_name_plural': 'Dados Meteorológicos Diários',
                'unique_together': {('estacao', 'data')},
            },
        ),
    ]
